language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.2
  - 7.4

matrix:
  include:
    - php: 7.4
      env: PHPCS=1

before_script: composer install --prefer-dist --dev

script:
  - sh -c "if [ '$PHPCS' != '1' ]; then vendor/bin/phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p -n --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi"

notifications:
  email: false
